### ISSUE TITLE
Blender 4.0.x and 4.1.x support ?

### ISSUE THREAD

**Issue by motorsep** [jensnt/io_import_build_map#2]
Is this wonderful add-on fully functional with latest Blender 4.x+ ?

**Comment by jensnt** [comment]
Hi!
Thanks for the question!
I checked and discovered that if you use the "Procedural Material Effects" option in Blender 4.1 or higher it will crash because Blender removed the Musgrave Texture node and merged it into the Noise texture node.

I just added a fix for that but still have to make a new release.
You can already get the fix if you download the code as a zip but I recommend waiting for the release.

Other than that I don't know of any issues in Blender 4.x :)

**Comment by jensnt** [comment]
Hi,
I just released version 1.2.0:
https://github.com/jensnt/io_import_build_map/releases

This should be fully compatible with Blender 4.1 and also has some other improvements.
Please don't hesitate to report any issues you might find. :)
